package com.example.iisdrugcrm.service;

import com.example.iisdrugcrm.domain.PricelistTeam;
import com.example.iisdrugcrm.domain.User;
import com.example.iisdrugcrm.dto.pricelist.PricelistActivityLogResponseDTO;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.springframework.stereotype.Service;

@Service
public class ActivityLogPdfExportService {

    private static final Color HEADER_BACKGROUND = new Color(230, 236, 245);
    private static final int DESCRIPTION_LIMIT = 140;

    private final PricelistActivityLogService activityLogService;
    private final PdfReportDisplayFormatter displayFormatter;

    public ActivityLogPdfExportService(
            PricelistActivityLogService activityLogService,
            PdfReportDisplayFormatter displayFormatter
    ) {
        this.activityLogService = activityLogService;
        this.displayFormatter = displayFormatter;
    }

    public byte[] generateActivityLogPdf(
            Long teamId,
            Long userId,
            OffsetDateTime from,
            OffsetDateTime to,
            String generatedBy
    ) {
        List<PricelistActivityLogResponseDTO> logs = activityLogService.findLogsForExport(teamId, userId, from, to);
        Map<Long, User> usersById = displayFormatter.usersById(userIds(logs, userId));
        Map<Long, PricelistTeam> teamsById = displayFormatter.teamsById(teamIds(logs, teamId));

        try {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4.rotate(), 24, 24, 32, 28);
            PdfWriter.getInstance(document, outputStream);
            document.open();

            addTitle(document);
            addMetadata(document, teamId, userId, from, to, generatedBy, logs.size(), usersById, teamsById);
            addLogTable(document, logs, usersById, teamsById);

            document.close();
            return outputStream.toByteArray();
        } catch (DocumentException exception) {
            throw new IllegalStateException("Unable to generate activity log PDF.", exception);
        }
    }

    private void addTitle(Document document) throws DocumentException {
        Paragraph title = new Paragraph("Activity Log Report", font(18, Font.BOLD));
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(14);
        document.add(title);
    }

    private void addMetadata(
            Document document,
            Long teamId,
            Long userId,
            OffsetDateTime from,
            OffsetDateTime to,
            String generatedBy,
            int totalEntries,
            Map<Long, User> usersById,
            Map<Long, PricelistTeam> teamsById
    ) throws DocumentException {
        PdfPTable table = table(2);
        table.addCell(labelCell("Generated at"));
        table.addCell(valueCell(displayFormatter.formatDateTime(OffsetDateTime.now())));
        table.addCell(labelCell("Generated by"));
        table.addCell(valueCell(displayFormatter.blankToDash(displayFormatter.formatUserByUsername(generatedBy))));
        table.addCell(labelCell("Applied filters"));
        table.addCell(valueCell(formatFilters(teamId, userId, from, to, usersById, teamsById)));
        table.addCell(labelCell("Exported entries"));
        table.addCell(valueCell(String.valueOf(totalEntries)));
        table.setSpacingAfter(14);
        document.add(table);
    }

    private void addLogTable(
            Document document,
            List<PricelistActivityLogResponseDTO> logs,
            Map<Long, User> usersById,
            Map<Long, PricelistTeam> teamsById
    ) throws DocumentException {
        PdfPTable table = table(8);
        table.setWidths(new float[] { 1.15f, 1.35f, 1.0f, 1.05f, 0.9f, 0.75f, 0.9f, 2.2f });
        table.setHeaderRows(1);

        table.addCell(headerCell("Date/time"));
        table.addCell(headerCell("User"));
        table.addCell(headerCell("Team"));
        table.addCell(headerCell("Action type"));
        table.addCell(headerCell("Entity type"));
        table.addCell(headerCell("Entity ID"));
        table.addCell(headerCell("Status"));
        table.addCell(headerCell("Description / details"));

        if (logs.isEmpty()) {
            PdfPCell emptyCell = valueCell("No activity logs found for selected filters");
            emptyCell.setColspan(8);
            table.addCell(emptyCell);
        } else {
            for (PricelistActivityLogResponseDTO log : logs) {
                table.addCell(smallCell(displayFormatter.formatDateTime(log.getTimestamp())));
                table.addCell(smallCell(displayFormatter.formatUser(log.getUserId(), usersById)));
                table.addCell(smallCell(displayFormatter.formatTeam(log.getTeamId(), teamsById)));
                table.addCell(smallCell(enumValue(log.getActionType())));
                table.addCell(smallCell("Pricelist"));
                table.addCell(smallCell(formatId(log.getPricelistId())));
                table.addCell(smallCell(formatStatusChange(log)));
                table.addCell(smallCell(truncate(log.getDescription())));
            }
        }

        document.add(table);
    }

    private PdfPTable table(int columns) {
        PdfPTable table = new PdfPTable(columns);
        table.setWidthPercentage(100);
        return table;
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font(10, Font.BOLD)));
        cell.setBackgroundColor(HEADER_BACKGROUND);
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font(8, Font.BOLD)));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(HEADER_BACKGROUND);
        cell.setPadding(5);
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text == null ? "" : text, font(10, Font.NORMAL)));
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell smallCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text == null ? "" : text, font(7, Font.NORMAL)));
        cell.setPadding(4);
        return cell;
    }

    private Font font(int size, int style) {
        return FontFactory.getFont(FontFactory.HELVETICA, "Cp1250", true, size, style, Color.BLACK);
    }

    private String formatFilters(
            Long teamId,
            Long userId,
            OffsetDateTime from,
            OffsetDateTime to,
            Map<Long, User> usersById,
            Map<Long, PricelistTeam> teamsById
    ) {
        return "Team: " + displayFormatter.formatTeamFilter(teamId, teamsById)
                + "; User: " + displayFormatter.formatUserFilter(userId, usersById)
                + "; From: " + (from == null ? "Any" : displayFormatter.formatDateTime(from))
                + "; To: " + (to == null ? "Any" : displayFormatter.formatDateTime(to));
    }

    private String formatId(Long id) {
        return id == null ? "-" : String.valueOf(id);
    }

    private String enumValue(Enum<?> value) {
        return value == null ? "-" : value.name();
    }

    private String formatStatusChange(PricelistActivityLogResponseDTO log) {
        String from = enumValue(log.getStatusFrom());
        String to = enumValue(log.getStatusTo());
        if ("-".equals(from) && "-".equals(to)) {
            return "-";
        }
        return from + " -> " + to;
    }

    private String truncate(String value) {
        if (value == null || value.length() <= DESCRIPTION_LIMIT) {
            return value;
        }
        return value.substring(0, DESCRIPTION_LIMIT - 3) + "...";
    }

    private List<Long> userIds(List<PricelistActivityLogResponseDTO> logs, Long userFilterId) {
        List<Long> ids = new ArrayList<>();
        if (userFilterId != null) {
            ids.add(userFilterId);
        }
        logs.stream().map(PricelistActivityLogResponseDTO::getUserId).filter(id -> id != null).forEach(ids::add);
        return ids;
    }

    private List<Long> teamIds(List<PricelistActivityLogResponseDTO> logs, Long teamFilterId) {
        List<Long> ids = new ArrayList<>();
        if (teamFilterId != null) {
            ids.add(teamFilterId);
        }
        logs.stream().map(PricelistActivityLogResponseDTO::getTeamId).filter(id -> id != null).forEach(ids::add);
        return ids;
    }
}
