package com.example.iisdrugcrm.service;

import com.example.iisdrugcrm.dto.pricelist.PricelistActivityLogResponseDTO;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import org.springframework.stereotype.Service;

@Service
public class ActivityLogPdfExportService {

    private static final DateTimeFormatter TIMESTAMP_FORMATTER = DateTimeFormatter.ISO_OFFSET_DATE_TIME;
    private static final Color HEADER_BACKGROUND = new Color(230, 236, 245);
    private static final int DESCRIPTION_LIMIT = 140;

    private final PricelistActivityLogService activityLogService;

    public ActivityLogPdfExportService(PricelistActivityLogService activityLogService) {
        this.activityLogService = activityLogService;
    }

    public byte[] generateActivityLogPdf(
            Long teamId,
            Long userId,
            OffsetDateTime from,
            OffsetDateTime to,
            String generatedBy
    ) {
        List<PricelistActivityLogResponseDTO> logs = activityLogService.findLogsForExport(teamId, userId, from, to);

        try {
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            Document document = new Document(PageSize.A4.rotate(), 24, 24, 32, 28);
            PdfWriter.getInstance(document, outputStream);
            document.open();

            addTitle(document);
            addMetadata(document, teamId, userId, from, to, generatedBy, logs.size());
            addLogTable(document, logs);

            document.close();
            return outputStream.toByteArray();
        } catch (DocumentException exception) {
            throw new IllegalStateException("Unable to generate activity log PDF.", exception);
        }
    }

    private void addTitle(Document document) throws DocumentException {
        Paragraph title = new Paragraph("Activity Log Report", font(18, Font.BOLD));
        title.setAlignment(Element.ALIGN_CENTER);
        title.setSpacingAfter(14);
        document.add(title);
    }

    private void addMetadata(
            Document document,
            Long teamId,
            Long userId,
            OffsetDateTime from,
            OffsetDateTime to,
            String generatedBy,
            int totalEntries
    ) throws DocumentException {
        PdfPTable table = table(2);
        table.addCell(labelCell("Generated at"));
        table.addCell(valueCell(formatTimestamp(OffsetDateTime.now(ZoneOffset.UTC))));
        table.addCell(labelCell("Generated by"));
        table.addCell(valueCell(blankToDash(generatedBy)));
        table.addCell(labelCell("Applied filters"));
        table.addCell(valueCell(formatFilters(teamId, userId, from, to)));
        table.addCell(labelCell("Exported entries"));
        table.addCell(valueCell(String.valueOf(totalEntries)));
        table.setSpacingAfter(14);
        document.add(table);
    }

    private void addLogTable(Document document, List<PricelistActivityLogResponseDTO> logs) throws DocumentException {
        PdfPTable table = table(8);
        table.setWidths(new float[] { 1.35f, 0.75f, 0.75f, 1.15f, 1.15f, 0.9f, 0.9f, 2.45f });
        table.setHeaderRows(1);

        table.addCell(headerCell("Date/time"));
        table.addCell(headerCell("User"));
        table.addCell(headerCell("Team"));
        table.addCell(headerCell("Action type"));
        table.addCell(headerCell("Entity type"));
        table.addCell(headerCell("Entity ID"));
        table.addCell(headerCell("Status"));
        table.addCell(headerCell("Description / details"));

        if (logs.isEmpty()) {
            PdfPCell emptyCell = valueCell("No activity logs found for selected filters");
            emptyCell.setColspan(8);
            table.addCell(emptyCell);
        } else {
            for (PricelistActivityLogResponseDTO log : logs) {
                table.addCell(smallCell(formatTimestamp(log.getTimestamp())));
                table.addCell(smallCell(formatId(log.getUserId())));
                table.addCell(smallCell(formatId(log.getTeamId())));
                table.addCell(smallCell(enumValue(log.getActionType())));
                table.addCell(smallCell("Pricelist"));
                table.addCell(smallCell(formatId(log.getPricelistId())));
                table.addCell(smallCell(formatStatusChange(log)));
                table.addCell(smallCell(truncate(log.getDescription())));
            }
        }

        document.add(table);
    }

    private PdfPTable table(int columns) {
        PdfPTable table = new PdfPTable(columns);
        table.setWidthPercentage(100);
        return table;
    }

    private PdfPCell labelCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font(10, Font.BOLD)));
        cell.setBackgroundColor(HEADER_BACKGROUND);
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell headerCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font(8, Font.BOLD)));
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        cell.setBackgroundColor(HEADER_BACKGROUND);
        cell.setPadding(5);
        return cell;
    }

    private PdfPCell valueCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text == null ? "" : text, font(10, Font.NORMAL)));
        cell.setPadding(6);
        return cell;
    }

    private PdfPCell smallCell(String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text == null ? "" : text, font(7, Font.NORMAL)));
        cell.setPadding(4);
        return cell;
    }

    private Font font(int size, int style) {
        return FontFactory.getFont(FontFactory.HELVETICA, "Cp1250", true, size, style, Color.BLACK);
    }

    private String formatFilters(Long teamId, Long userId, OffsetDateTime from, OffsetDateTime to) {
        return "Team: " + (teamId == null ? "All teams" : "Team ID " + teamId)
                + "; User: " + (userId == null ? "All users" : "User ID " + userId)
                + "; From: " + (from == null ? "Any" : formatTimestamp(from))
                + "; To: " + (to == null ? "Any" : formatTimestamp(to));
    }

    private String formatTimestamp(OffsetDateTime timestamp) {
        return timestamp == null ? "-" : TIMESTAMP_FORMATTER.format(timestamp.withOffsetSameInstant(ZoneOffset.UTC));
    }

    private String formatId(Long id) {
        return id == null ? "-" : String.valueOf(id);
    }

    private String enumValue(Enum<?> value) {
        return value == null ? "-" : value.name();
    }

    private String formatStatusChange(PricelistActivityLogResponseDTO log) {
        String from = enumValue(log.getStatusFrom());
        String to = enumValue(log.getStatusTo());
        if ("-".equals(from) && "-".equals(to)) {
            return "-";
        }
        return from + " -> " + to;
    }

    private String truncate(String value) {
        if (value == null || value.length() <= DESCRIPTION_LIMIT) {
            return value;
        }
        return value.substring(0, DESCRIPTION_LIMIT - 3) + "...";
    }

    private String blankToDash(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}
