package com.example.iisdrugcrm.domain;

public enum UserRole {
    ROLE_ADMIN,
    ROLE_PRICELIST_CREATOR,
    ROLE_PORTFOLIO_MANAGER,
    ROLE_BUYER,

    ROLE_SALES_REPRESENTATIVE,
    ROLE_ACCOUNT_MANAGER,
    ROLE_SALES_MANAGER,

    
    ROLE_LEKAR,
    ROLE_PACIJENT,
    ROLE_FARMAKOVIGILANT
}